field.formatter.settings.text_copier:
  type: mapping
  label: 'Trimmed text display format settings'
  mapping:
    copy_button_label:
      type: string
      label: "Copy button label"
    copied_button_label:
      type: string
      label: "Copied button label"
    disable_time:
      type: integer
      label: "Button disable time"
